In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size) for words in sent ]
print(onehot_repr)

[[2049, 4302, 4748, 3151], [2049, 4302, 4748, 2320], [2049, 6270, 4748, 8069], [632, 3276, 9037, 6973, 5097], [632, 3276, 9037, 6973, 7333], [3186, 2049, 2253, 4748, 3247], [8243, 4286, 4610, 6973]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2049 4302 4748 3151]
 [   0    0    0    0 2049 4302 4748 2320]
 [   0    0    0    0 2049 6270 4748 8069]
 [   0    0    0  632 3276 9037 6973 5097]
 [   0    0    0  632 3276 9037 6973 7333]
 [   0    0    0 3186 2049 2253 4748 3247]
 [   0    0    0    0 8243 4286 4610 6973]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-0.04732115 -0.02233481  0.04672765  0.03313558 -0.03840084
   -0.04607862 -0.03846657  0.03152796  0.04900165  0.03653138]
  [-0.04732115 -0.02233481  0.04672765  0.03313558 -0.03840084
   -0.04607862 -0.03846657  0.03152796  0.04900165  0.03653138]
  [-0.04732115 -0.02233481  0.04672765  0.03313558 -0.03840084
   -0.04607862 -0.03846657  0.03152796  0.04900165  0.03653138]
  [-0.04732115 -0.02233481  0.04672765  0.03313558 -0.03840084
   -0.04607862 -0.03846657  0.03152796  0.04900165  0.03653138]
  [-0.02866486 -0.02529279  0.01694355  0.04656806 -0.01960623
   -0.02289655  0.03755784 -0.01222472  0.04678902 -0.03089173]
  [-0.04608114 -0.0004648  -0.02641598  0.01136877 -0.02931418
    0.02599367 -0.02138326  0.02554491  0.01183679  0.01353708]
  [-0.006881   -0.0396803   0.01139388 -0.03160143  0.04088868
   -0.02783525  0.04822195  0.03442457  0.01455222 -0.00733963]
  [-0.00252325  0.01880899 -0.00265838  0.00785517  0.03578774
   -0.01717191  0.03530848  0.01587992  0.029690

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 2049, 4302, 4748, 3151])

In [14]:
print(model.predict(embedded_docs)[0])

[[-0.04732115 -0.02233481  0.04672765  0.03313558 -0.03840084 -0.04607862
  -0.03846657  0.03152796  0.04900165  0.03653138]
 [-0.04732115 -0.02233481  0.04672765  0.03313558 -0.03840084 -0.04607862
  -0.03846657  0.03152796  0.04900165  0.03653138]
 [-0.04732115 -0.02233481  0.04672765  0.03313558 -0.03840084 -0.04607862
  -0.03846657  0.03152796  0.04900165  0.03653138]
 [-0.04732115 -0.02233481  0.04672765  0.03313558 -0.03840084 -0.04607862
  -0.03846657  0.03152796  0.04900165  0.03653138]
 [-0.02866486 -0.02529279  0.01694355  0.04656806 -0.01960623 -0.02289655
   0.03755784 -0.01222472  0.04678902 -0.03089173]
 [-0.04608114 -0.0004648  -0.02641598  0.01136877 -0.02931418  0.02599367
  -0.02138326  0.02554491  0.01183679  0.01353708]
 [-0.006881   -0.0396803   0.01139388 -0.03160143  0.04088868 -0.02783525
   0.04822195  0.03442457  0.01455222 -0.00733963]
 [-0.00252325  0.01880899 -0.00265838  0.00785517  0.03578774 -0.01717191
   0.03530848  0.01587992  0.02969087 -0.01555209]]